### ISSUE TITLE
jetpack symlink breaks NPM install on Windows

### ISSUE THREAD

**Issue by csosborn** [Gozala/reactor-commonjs#1]
Do you know if anyone/anything uses the jetpack symlink in /engines? Node.js doesn't need it, but it breaks NPM on windows (apparently it can't handle symlinks). This is more NPM's problem than yours, obviously, but if you can help by dropping the link that would be great. 

Thanks!

**Comment by Gozala** [comment]
Just published version 0.2.0 to npm with this being fixed. Thank for the report @csosborn

**Comment by csosborn** [comment]
Thank you very much for the quick turnaround!
